# Generated by Django 4.2.16 on 2024-10-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='author_image',
            field=models.ImageField(default=2002, upload_to='author/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='book_file',
            field=models.FileField(default=2002, upload_to='files/books/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='cover_image',
            field=models.ImageField(default=0, upload_to='books/'),
            preserve_default=False,
        ),
    ]
